using UnityEngine;
using System.Collections;
using System.IO;
using UnityEditor;
using System.Xml.Serialization;
using NPOI.HSSF.UserModel;
using NPOI.XSSF.UserModel;
using NPOI.SS.UserModel;

public class Scenario_Sheet_importer : AssetPostprocessor {
	private static readonly string filePath = "Assets/ExcelData/Scenario_Sheet.xls";
	private static readonly string exportPath = "Assets/ExcelData/Scenario_Sheet.asset";
	private static readonly string[] sheetNames = { "tutorial","Scenario1","Scenario2","Scenario3","Scenario4","AutoGeneratedScenario", };
	
	static void OnPostprocessAllAssets (string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
	{
		foreach (string asset in importedAssets) {
			if (!filePath.Equals (asset))
				continue;
				
			GuideList data = (GuideList)AssetDatabase.LoadAssetAtPath (exportPath, typeof(GuideList));
			if (data == null) {
				data = ScriptableObject.CreateInstance<GuideList> ();
				AssetDatabase.CreateAsset ((ScriptableObject)data, exportPath);
				data.hideFlags = HideFlags.NotEditable;
			}
			
			data.sheets.Clear ();
			using (FileStream stream = File.Open (filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite)) {
				IWorkbook book = null;
				if (Path.GetExtension (filePath) == ".xls") {
					book = new HSSFWorkbook(stream);
				} else {
					book = new XSSFWorkbook(stream);
				}
				
				foreach(string sheetName in sheetNames) {
					ISheet sheet = book.GetSheet(sheetName);
					if( sheet == null ) {
						Debug.LogError("[QuestData] sheet not found:" + sheetName);
						continue;
					}

					GuideList.Sheet s = new GuideList.Sheet ();
					s.name = sheetName;
				
					for (int i=1; i<= sheet.LastRowNum; i++) {
						IRow row = sheet.GetRow (i);
						ICell cell = null;
						
						GuideList.Param p = new GuideList.Param ();
						
					cell = row.GetCell(0); p.id = (cell == null ? 0.0 : cell.NumericCellValue);
					cell = row.GetCell(1); p.guide = (cell == null ? "" : cell.StringCellValue);
					cell = row.GetCell(2); p.voice = (cell == null ? "" : cell.StringCellValue);
					cell = row.GetCell(3); p.voice_content = (cell == null ? "" : cell.StringCellValue);
						s.list.Add (p);
					}
					data.sheets.Add(s);
				}
			}

			ScriptableObject obj = AssetDatabase.LoadAssetAtPath (exportPath, typeof(ScriptableObject)) as ScriptableObject;
			EditorUtility.SetDirty (obj);
		}
	}
}
